name: Static Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use PHP 8.3
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run Static Analysis with Larastan (PHPStan)
        run: ./vendor/bin/phpstan --error-format=github

      - name: Run Code Quality Analysis with Laravel Pint
        run: ./vendor/bin/pint --test
